-- Web3 crowdfunding app bootstrap for Supabase
-- Run this in the Supabase SQL editor for the project used by client/.env.
-- This app currently uses the anon key directly from the browser and does not use Supabase Auth.
-- Because of that, the policies below are intentionally open to the anon role.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    wallet_address text not null,
    name text not null,
    profile_image_url text,
    created_at timestamptz not null default now()
);

create unique index if not exists users_wallet_address_lower_key
    on public.users (lower(wallet_address));

create table if not exists public.campaigns (
    address text primary key,
    creator_address text,
    title text,
    description text,
    target_eth numeric,
    duration_days integer,
    image_url text,
    created_at timestamptz not null default now()
);

create unique index if not exists campaigns_address_lower_key
    on public.campaigns (lower(address));

alter table public.campaigns
    add column if not exists image_url text;

create table if not exists public.donations (
    id bigint generated by default as identity primary key,
    donor_address text not null,
    campaign_address text not null,
    amount_eth numeric not null,
    created_at timestamptz not null default now()
);

create index if not exists donations_donor_address_idx
    on public.donations (lower(donor_address));

create index if not exists donations_campaign_address_idx
    on public.donations (lower(campaign_address));

create table if not exists public.refunds (
    id bigint generated by default as identity primary key,
    campaign_address text not null,
    user_address text not null,
    amount_eth numeric not null,
    tx_hash text,
    created_at timestamptz not null default now()
);

create index if not exists refunds_user_address_idx
    on public.refunds (lower(user_address));

create index if not exists refunds_campaign_address_idx
    on public.refunds (lower(campaign_address));

alter table public.users enable row level security;
alter table public.campaigns enable row level security;
alter table public.donations enable row level security;
alter table public.refunds enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'users' and policyname = 'users_select_all'
    ) then
        create policy users_select_all on public.users
            for select to anon, authenticated using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'users' and policyname = 'users_insert_all'
    ) then
        create policy users_insert_all on public.users
            for insert to anon, authenticated with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'users' and policyname = 'users_update_all'
    ) then
        create policy users_update_all on public.users
            for update to anon, authenticated using (true) with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'campaigns' and policyname = 'campaigns_select_all'
    ) then
        create policy campaigns_select_all on public.campaigns
            for select to anon, authenticated using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'campaigns' and policyname = 'campaigns_insert_all'
    ) then
        create policy campaigns_insert_all on public.campaigns
            for insert to anon, authenticated with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'campaigns' and policyname = 'campaigns_update_all'
    ) then
        create policy campaigns_update_all on public.campaigns
            for update to anon, authenticated using (true) with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'donations' and policyname = 'donations_select_all'
    ) then
        create policy donations_select_all on public.donations
            for select to anon, authenticated using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'donations' and policyname = 'donations_insert_all'
    ) then
        create policy donations_insert_all on public.donations
            for insert to anon, authenticated with check (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'refunds' and policyname = 'refunds_select_all'
    ) then
        create policy refunds_select_all on public.refunds
            for select to anon, authenticated using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'refunds' and policyname = 'refunds_insert_all'
    ) then
        create policy refunds_insert_all on public.refunds
            for insert to anon, authenticated with check (true);
    end if;
end $$;

insert into storage.buckets (id, name, public)
values ('app-media', 'app-media', true)
on conflict (id) do update
set public = excluded.public;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage' and tablename = 'objects' and policyname = 'app_media_select_all'
    ) then
        create policy app_media_select_all on storage.objects
            for select to anon, authenticated
            using (bucket_id = 'app-media');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage' and tablename = 'objects' and policyname = 'app_media_insert_all'
    ) then
        create policy app_media_insert_all on storage.objects
            for insert to anon, authenticated
            with check (bucket_id = 'app-media');
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'storage' and tablename = 'objects' and policyname = 'app_media_update_all'
    ) then
        create policy app_media_update_all on storage.objects
            for update to anon, authenticated
            using (bucket_id = 'app-media')
            with check (bucket_id = 'app-media');
    end if;
end $$;
